#tomcat服务器配置
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 18081
    servlet:
        context-path: /

#默认使用配置
spring:
  profiles:
    #这是说明使用配置文件为application-dev.yml文件，如数据库配置
    # dev - 普通开发环境 pro - 生产环境配置 tmp - 临时开发环境
    active: pro

  mvc:
    static-path-pattern: /**
  resources:
    # 这里设置要指向的路径，多个使用英文逗号隔开
    # 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/templates/,classpath:/WSDLFiles/

  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:      # 密码（默认为空）
      timeout: 6000  # 连接超时时长（毫秒）
      jedis:
          pool:
              max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
              max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
              max-idle: 10      # 连接池中的最大空闲连接
              min-idle: 5       # 连接池中的最小空闲连接

  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix:
      encoding: UTF-8
      content-type: text/html
      mode: LEGACYHTML5
  jmx:
      enabled: false
  http:
      multipart:
        enabled: true
        max-file-size: 100MB
        max-request-size: 200MB


#配置日志
logging:
  #配置日志文件路径
  path: ../log
  level:
    #不同目录下的日志可配置不同级别
    com.buf.main.mapper: TRACE
    org.springfromework.web: info
    com.buf.data.dao: TRACE
    com.buf.datasource.secondDao: TRACE
#    org.hibernate: error

system:
    redis:
        open: false  # 是否开启redis缓存  true开启   false关闭
    shiro:
        redis: false # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】
pagehelper:
         helperDialect: mysql
         reasonable: true
         supportMethodsArguments: true
         params: count=countSql
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**dao.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.buf.**.dao
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
#    capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.dao.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
  config-location:
    classpath:configuration.xml

#文件上传到服务器的路径
web:
  upload-path: D:/upload-files/
  upload-path-linux: /app/uploadFiles/

serverPath:
  filePath: ${web.upload-path}
  #清除前多少天的下载文件
  deleteDay: -7