
package com.buf.LoginWebService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ydzyServicePortType", targetNamespace = "http://ydzyService.webservice.ep")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface YdzyServicePortType {


    /**
     * 
     * @param param0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:sgpmsGetData")
    @WebResult(targetNamespace = "http://ydzyService.webservice.ep")
    @RequestWrapper(localName = "sgpmsGetData", targetNamespace = "http://ydzyService.webservice.ep", className = "LoginWebService.SgpmsGetData")
    @ResponseWrapper(localName = "sgpmsGetDataResponse", targetNamespace = "http://ydzyService.webservice.ep", className = "LoginWebService.SgpmsGetDataResponse")
    public String sgpmsGetData(
        @WebParam(name = "param0", targetNamespace = "http://ydzyService.webservice.ep")
        String param0);

}
