
package com.buf.LoginWebService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ydzyService", targetNamespace = "http://ydzyService.webservice.ep", wsdlLocation = "http://10.160.8.60:17021/content/services/ydzyService?wsdl")
public class YdzyService
    extends Service
{

    private final static URL YDZYSERVICE_WSDL_LOCATION;
    private final static WebServiceException YDZYSERVICE_EXCEPTION;
    private final static QName YDZYSERVICE_QNAME = new QName("http://ydzyService.webservice.ep", "ydzyService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.160.8.60:17021/content/services/ydzyService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        YDZYSERVICE_WSDL_LOCATION = url;
        YDZYSERVICE_EXCEPTION = e;
    }

    public YdzyService() {
        super(__getWsdlLocation(), YDZYSERVICE_QNAME);
    }

    public YdzyService(WebServiceFeature... features) {
        super(__getWsdlLocation(), YDZYSERVICE_QNAME, features);
    }

    public YdzyService(URL wsdlLocation) {
        super(wsdlLocation, YDZYSERVICE_QNAME);
    }

    public YdzyService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, YDZYSERVICE_QNAME, features);
    }

    public YdzyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public YdzyService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns YdzyServicePortType
     */
    @WebEndpoint(name = "ydzyServiceHttpSoap11Endpoint")
    public YdzyServicePortType getYdzyServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://ydzyService.webservice.ep", "ydzyServiceHttpSoap11Endpoint"), YdzyServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns YdzyServicePortType
     */
    @WebEndpoint(name = "ydzyServiceHttpSoap11Endpoint")
    public YdzyServicePortType getYdzyServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://ydzyService.webservice.ep", "ydzyServiceHttpSoap11Endpoint"), YdzyServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns YdzyServicePortType
     */
    @WebEndpoint(name = "ydzyServiceHttpEndpoint")
    public YdzyServicePortType getYdzyServiceHttpEndpoint() {
        return super.getPort(new QName("http://ydzyService.webservice.ep", "ydzyServiceHttpEndpoint"), YdzyServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns YdzyServicePortType
     */
    @WebEndpoint(name = "ydzyServiceHttpEndpoint")
    public YdzyServicePortType getYdzyServiceHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://ydzyService.webservice.ep", "ydzyServiceHttpEndpoint"), YdzyServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns YdzyServicePortType
     */
    @WebEndpoint(name = "ydzyServiceHttpSoap12Endpoint")
    public YdzyServicePortType getYdzyServiceHttpSoap12Endpoint() {
        return super.getPort(new QName("http://ydzyService.webservice.ep", "ydzyServiceHttpSoap12Endpoint"), YdzyServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns YdzyServicePortType
     */
    @WebEndpoint(name = "ydzyServiceHttpSoap12Endpoint")
    public YdzyServicePortType getYdzyServiceHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://ydzyService.webservice.ep", "ydzyServiceHttpSoap12Endpoint"), YdzyServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (YDZYSERVICE_EXCEPTION!= null) {
            throw YDZYSERVICE_EXCEPTION;
        }
        return YDZYSERVICE_WSDL_LOCATION;
    }

}
